### ISSUE TITLE
404 error code

### ISSUE THREAD

**Issue by ghost** [espadrine/New-In-A-Spec#6]
When I click on the link under "Latest Editor's Draft" it produces a 404 error code. I don't know if this error occurs for every user.
![image](https://cloud.githubusercontent.com/assets/13663148/9269844/04e8af66-4265-11e5-80c9-f71524a5eb73.png)

Here is the result:
![image](https://cloud.githubusercontent.com/assets/13663148/9269857/19c62bde-4265-11e5-9b6f-898c6324a448.png)

**Comment by espadrine** [comment]
It should now be fixed.
