### ISSUE TITLE
Updated links

### ISSUE THREAD

**Issue by ghost** [espadrine/New-In-A-Spec#7]
The links in the "contents" area at the top of the page haven't been updated for more than three years, I am inputting the latest ones to rectify this issue. If requested I would love to place the new links into the codebase.

Updated links:

<dl>
        <dt>This Version:</dt>
        <dd class="publish"><a href="http://www.w3.org/TR/2014/NOTE-html5-diff-20141209/">http://www.w3.org/TR/2014/NOTE-html5-diff-20141209/</a></dd>
        <dt class="publish">Latest Version:</dt>
        <dd class="publish"><a href="http://www.w3.org/TR/html5-diff/">http://www.w3.org/TR/html5-diff/</a></dd>

        <dt>Previous Versions:</dt>
        <dd><a href="http://www.w3.org/TR/2014/WD-html5-diff-20140918/">http://www.w3.org/TR/2014/WD-html5-diff-20140918/</a></dd>
        <dd><a href="http://http://www.w3.org/TR/2013/WD-html5-diff-20130528/">http://http://www.w3.org/TR/2013/WD-html5-diff-20130528/</a></dd>
        <dd><a href="http://www.w3.org/TR/2012/WD-html5-diff-20121025/">http://www.w3.org/TR/2012/WD-html5-diff-20121025/</a></dd>
        <dd><a href="http://www.w3.org/TR/2012/WD-html5-diff-20120329/">http://www.w3.org/TR/2012/WD-html5-diff-20120329/</a></dd>
        <dd><a href="http://www.w3.org/TR/2011/WD-html5-diff-20110525/">http://www.w3.org/TR/2011/WD-html5-diff-20110525/</a></dd>
        <dd><a href="http://www.w3.org/TR/2011/WD-html5-diff-20110405/">http://www.w3.org/TR/2011/WD-html5-diff-20110405/</a></dd>
        <dd><a href="http://www.w3.org/TR/2011/WD-html5-diff-20110113/">http://www.w3.org/TR/2011/WD-html5-diff-20110113/</a></dd>
        <dd><a href="http://www.w3.org/TR/2010/WD-html5-diff-20101019/">http://http://www.w3.org/TR/2010/WD-html5-diff-20101019/</a></dd>
        <dd><a href="http://www.w3.org/TR/2010/WD-html5-diff-20100624/">http://www.w3.org/TR/2010/WD-html5-diff-20100624/</a></dd>
        <dd><a href="http://www.w3.org/TR/2010/WD-html5-diff-20100304/">http://www.w3.org/TR/2010/WD-html5-diff-20100304/</a></dd>
        <dd><a href="http://www.w3.org/TR/2009/WD-html5-diff-20090825/">http://www.w3.org/TR/2009/WD-html5-diff-20090825/</a></dd>
        <dd><a href="http://www.w3.org/TR/2009/WD-html5-diff-20090423/">http://www.w3.org/TR/2009/WD-html5-diff-20090423/</a></dd>
         <dd><a href="http://www.w3.org/TR/2009/WD-html5-diff-20090212/">http://www.w3.org/TR/2009/WD-html5-diff-20090212/</a></dd>
         <dd><a href="http://www.w3.org/TR/2008/WD-html5-diff-20080610/">http://www.w3.org/TR/2008/WD-html5-diff-20080610/</a></dd>
         <dd><a href="http://www.w3.org/TR/2008/WD-html5-diff-20080122/">http://www.w3.org/TR/2008/WD-html5-diff-20080122/</a></dd>
</dl>

**Comment by espadrine** [comment]
You can definitely do a pull request to get credit for your work!

(If you don't want to do a PR, I'll do it, in which case thanks!)

**Comment by znawk** [comment]
Pull request has been made.
